### ISSUE TITLE
README missing unattended-upgrades

### ISSUE THREAD

**Issue by kq01526** [Utappia/uCareSystem#18]
@cerebrux 

As someone else had already requested in https://answers.launchpad.net/2clickupdate/+question/157426 , it would be nice to use ucaresystem-core as an alternative for unattended-upgrades.

I realize that unattended upgrades should be done through unattended-upgrades ideally, but unattended-upgrades is not so reliable (and it isn't even enabled for all packages by default and does not even auto-remove old kernels by default).

What do you think would be the best way to use run ucaresystem-core unattended?

Adding it to the autostart and adding an exception for ucaresystem-core in the sudoers file?

Or adding ucaresystem-core to rc.local?

What would you recommend?

Regards

**Comment by cerebrux** [comment]
Unattended-upgrades should be configured on a system level. It is more sophisticated as it can detect if user has chosen to shut down the computer. 

In contrast, on a server this is not an issue (as they newer shutdown) and as a sysadmin you can add ucaresystem-core to a cron job.
Also, on Ubuntu Desktop/Server, if I remember correctly, auto-installation of Security updates are enabled by default. This is more crucial than regular updates.

So It is more important to use ucaresystem-core manually on a desktop/laptop than adding it to cron job. But that is somthing to be decided by the user, as for example I have added ucersystem-core to the cron job because I rarely shut down my Workstation.
